In [1]:
import numpy as np

## Numpy Arrays

In [2]:
benimListem=[10,20,30,40]

In [3]:
np.array(benimListem)

array([10, 20, 30, 40])

In [4]:
matrix=[[10,20,30],[20,30,40],[30,40,50]]

In [5]:
np.array(matrix)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Zeros

## Zeros

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Linspace

In [16]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

## eye

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random 

In [19]:
np.random.randn(2)

array([-0.80732923,  0.87410012])

In [20]:
np.random.randn(4,4)

array([[ 0.27836905, -1.70151067, -0.96876728,  1.55578274],
       [ 0.03519169, -0.53708859,  0.72085323, -0.6882806 ],
       [-2.62029581, -1.02300414, -0.34114496,  0.26581922],
       [ 1.48973748,  1.50026471,  0.57518293,  0.02475693]])

In [25]:
np.random.randint(1,10)

4

In [26]:
benimNumpyDizim=np.arange(30)

In [27]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Numpy Dizi Metodları 

In [28]:
benimRandomDizim=np.random.randint(0,100,20)

In [29]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
benimRandomDizim

array([ 7, 75,  0, 42, 23, 14, 47, 51, 10, 45, 74, 39, 29, 58, 77, 31,  3,
       65, 35, 97])

In [31]:
benimRandomDizim.max()

97

In [32]:
benimRandomDizim.min()

0

In [33]:
benimRandomDizim.argmax()

19

In [34]:
benimRandomDizim.argmin()

2

In [35]:
benimNumpyDizim.shape

(30,)

## Numpy Operasyonlar

In [36]:
benimDizim=np.arange(0,15)

In [37]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
benimDizim[5]

5

In [40]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [42]:
benimDizim[3:8]=-5

In [43]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [44]:
baskaDizi=np.arange(0,24)

In [45]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
slicingDizisi=baskaDizi[4:9]

In [51]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [53]:
slicingDizisi[:]=700

In [54]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [55]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## Matrix

In [65]:
benimList=[[10,20,30],[40,50,60],[70,80,90]]

In [66]:
benimMatrix=np.array(benimList)

In [67]:
benimMatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [68]:
benimMatrix[0][1]

20

In [69]:
benimMatrix[0,1]

20

In [71]:
benimMatrix[0:,2]

array([30, 60, 90])

In [73]:
benimMatrix[2:,2:]

array([[90]])

## Operasyon

In [76]:
yeniDizi=np.random.randint(1,100,20)

In [77]:
yeniDizi

array([97, 90, 65, 17, 16, 88, 12, 31, 58, 28, 35, 53, 60, 97, 52, 66, 26,
       26, 87, 85])

In [78]:
yeniDizi>24

array([ True,  True,  True, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [79]:
yeniDizi[yeniDizi>24]

array([97, 90, 65, 88, 31, 58, 28, 35, 53, 60, 97, 52, 66, 26, 26, 87, 85])

In [80]:
yeniDizi

array([97, 90, 65, 17, 16, 88, 12, 31, 58, 28, 35, 53, 60, 97, 52, 66, 26,
       26, 87, 85])

In [81]:
sonDizi=np.arange(0,24)

In [82]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [83]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [84]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [85]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [86]:
sonDizi/sonDizi

<ipython-input-86-7d5697280f2b>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [88]:
np.max(sonDizi)

23

In [89]:
np.min(sonDizi)

0